### ISSUE TITLE
Characters mirrored

### ISSUE THREAD

**Issue by MadNBG** [alanswx/WebPixelFrame#5]
Hello,
I got an Issue: all the characters are mirrored.
They scroll, the have Color, but the are mirrored. 

Can you help me, please?

Kind regards from Baden, Germany
MadNBG

**Comment by alanswx** [comment]
I believe it depends on how you wired the display. Or if you purchased a pre wired o e how they wired it. 

There is a option to change this, see:
https://github.com/alanswx/WebPixelFrame/blob/master/WebPixelFrame/DisplayPixels.h#L14

**Comment by MadNBG** [comment]
Hi, 
Thanks  - that was the Right hint. Know it's working.
My second self-compiled pice which works :-)

**Comment by alanswx** [comment]
Glad you got it working! Happy to see the code is being used.
